1.Importing the required libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


2.Load the dataset

In [2]:
dataset = pd.read_csv("/Users/user/Documents/Fraud_detection/Churn_Modelling.csv")
dataset

RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

3.Feature selection

In [3]:
X = dataset.iloc[:, 3:13].values
Y = dataset.iloc[:,-1].values

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
X.shape

(10000, 10)

In [6]:
Y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

4.Encoding the Dataset

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])
onehotencoder = OneHotEncoder(categorical_features= [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:,1:]


5.Splitting the dataset into train and test set

In [9]:

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

6.Normalizing the dataset(Feature Scaling)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

7.Build the ANN using keras



In [11]:
import keras
from keras.models import Sequential #for initializing ANN models
from keras.layers import Dense

#Initializing ANN
classifier = Sequential()

#Forward propogation
#Adding layers #First hidden layer
classifier.add(Dense(output_dim = 6, init = 'random_uniform', activation= 'relu', input_dim = 11))

#Adding second hidden layer
classifier.add(Dense(output_dim = 6, init = 'random_uniform', activation= 'relu'))

#Adding output layer
classifier.add(Dense(output_dim = 1, init = 'random_uniform' ,activation= 'sigmoid'))



Using TensorFlow backend.
C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="random_uniform")`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="random_uniform")`
  del sys.path[0]
C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="random_uniform")`
  app.launch_new_instance()


8.Calculate loss and update parameters

In [12]:
classifier.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics = ['accuracy'])


In [13]:
y_pred = classifier.predict(X_train)
y_pred = (y_pred > 0.5)

9.Predict the accuracy 

In [14]:
classifier.fit(X_train, Y_train, batch_size= 20, epochs = 100)


Epoch 1/100
8000/8000 [==============================] - 2s - loss: 0.5251 - acc: 0.7945     
Epoch 2/100
8000/8000 [==============================] - 1s - loss: 0.4331 - acc: 0.7960     
Epoch 3/100
8000/8000 [==============================] - 0s - loss: 0.4269 - acc: 0.7960     
Epoch 4/100
8000/8000 [==============================] - 0s - loss: 0.4213 - acc: 0.8083     
Epoch 5/100
8000/8000 [==============================] - 0s - loss: 0.4161 - acc: 0.8249     
Epoch 6/100
8000/8000 [==============================] - 0s - loss: 0.4123 - acc: 0.8304     
Epoch 7/100
8000/8000 [==============================] - 0s - loss: 0.4093 - acc: 0.8300     
Epoch 8/100
8000/8000 [==============================] - 0s - loss: 0.4070 - acc: 0.8319     
Epoch 9/100
8000/8000 [==============================] - 0s - loss: 0.4056 - acc: 0.8336     
Epoch 10/100
8000/8000 [==============================] - 0s - loss: 0.4040 - acc: 0.8334     
Epoch 11/100
8000/8000 [==============================] - 0

8000/8000 [==============================] - 0s - loss: 0.3413 - acc: 0.8611     
Epoch 88/100
8000/8000 [==============================] - 0s - loss: 0.3403 - acc: 0.8596     
Epoch 89/100
8000/8000 [==============================] - 0s - loss: 0.3404 - acc: 0.8588     
Epoch 90/100
8000/8000 [==============================] - 0s - loss: 0.3401 - acc: 0.8594     
Epoch 91/100
8000/8000 [==============================] - 0s - loss: 0.3410 - acc: 0.8600     
Epoch 92/100
8000/8000 [==============================] - 0s - loss: 0.3399 - acc: 0.8597     
Epoch 93/100
8000/8000 [==============================] - 0s - loss: 0.3398 - acc: 0.8611     
Epoch 94/100
8000/8000 [==============================] - 0s - loss: 0.3407 - acc: 0.8585     
Epoch 95/100
8000/8000 [==============================] - 0s - loss: 0.3401 - acc: 0.8620     
Epoch 96/100
8000/8000 [==============================] - 0s - loss: 0.3392 - acc: 0.8601     
Epoch 97/100
8000/8000 [==============================] - 0s - 

In [ ]:
classifier.fit(X_test, Y_test, epochs = 100)

Epoch 1/100
2000/2000 [==============================] - 0s - loss: 0.3350 - acc: 0.8610     
Epoch 2/100
2000/2000 [==============================] - 0s - loss: 0.3290 - acc: 0.8645     
Epoch 3/100
2000/2000 [==============================] - 0s - loss: 0.3276 - acc: 0.8630     
Epoch 4/100
2000/2000 [==============================] - 0s - loss: 0.3262 - acc: 0.8695     
Epoch 5/100
2000/2000 [==============================] - 0s - loss: 0.3253 - acc: 0.8665     
Epoch 6/100
2000/2000 [==============================] - 0s - loss: 0.3248 - acc: 0.8660     
Epoch 7/100
2000/2000 [==============================] - 0s - loss: 0.3241 - acc: 0.8665     
Epoch 8/100
2000/2000 [==============================] - 0s - loss: 0.3233 - acc: 0.8670     
Epoch 9/100
2000/2000 [==============================] - 0s - loss: 0.3226 - acc: 0.8720     
Epoch 10/100
2000/2000 [==============================] - 0s - loss: 0.3223 - acc: 0.8650     
Epoch 11/100
2000/2000 [==============================] - 0

In [121]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)


Epoch 1/100
2000/2000 [==============================] - 0s - loss: 0.3700 - acc: 0.8495     
Epoch 2/100
2000/2000 [==============================] - 0s - loss: 0.3699 - acc: 0.8495     
Epoch 3/100
2000/2000 [==============================] - 0s - loss: 0.3699 - acc: 0.8505     
Epoch 4/100
2000/2000 [==============================] - 0s - loss: 0.3702 - acc: 0.8510     
Epoch 5/100
2000/2000 [==============================] - 0s - loss: 0.3699 - acc: 0.8500     
Epoch 6/100
2000/2000 [==============================] - 0s - loss: 0.3697 - acc: 0.8495     
Epoch 7/100
2000/2000 [==============================] - 0s - loss: 0.3698 - acc: 0.8505     
Epoch 8/100
2000/2000 [==============================] - 0s - loss: 0.3696 - acc: 0.8495     
Epoch 9/100
2000/2000 [==============================] - 0s - loss: 0.3701 - acc: 0.8495     
Epoch 10/100
2000/2000 [==============================] - 0s - loss: 0.3698 - acc: 0.8500     
Epoch 11/100
2000/2000 [==============================] - 0

In [109]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)

In [110]:
cm

array([[1544,   51],
       [ 258,  147]], dtype=int64)